"""rename search history query field

Revision ID: 32a0a9c5fdbb
Revises: 4ec014eb6268
Create Date: 2026-05-17 01:58:30.715914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a0a9c5fdbb'
down_revision = '4ec014eb6268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_text', sa.String(length=120), nullable=False))
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('search_text')

    # ### end Alembic commands ###
