"""add changes

Revision ID: 585ab3e2b140
Revises: da6bac5bb00c
Create Date: 2026-05-08 12:31:12.011160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585ab3e2b140'
down_revision = 'da6bac5bb00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
