"""add itinerary photo table

Revision ID: 5f2fb1ed177a
Revises: 585ab3e2b140
Create Date: 2026-05-12 15:15:11.142155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2fb1ed177a'
down_revision = '585ab3e2b140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_day_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary_photo')
    # ### end Alembic commands ###
