"""update itinerary table

Revision ID: 75acb16201ee
Revises: 
Create Date: 2026-05-07 19:53:04.936789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75acb16201ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('destination', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('travel_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('budget')
        batch_op.drop_column('travel_style')
        batch_op.drop_column('destination')
        batch_op.drop_column('creator_name')

    # ### end Alembic commands ###
