"""migration

Revision ID: 916321e5d34f
Revises: 043ce36cdba3
Create Date: 2026-05-14 20:16:29.286887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916321e5d34f'
down_revision = '043ce36cdba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_column('creator_name')

    with op.batch_alter_table('itinerary_day', schema=None) as batch_op:
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_name', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###