"""add reaction to messages

Revision ID: da6bac5bb00c
Revises: 75acb16201ee
Create Date: 2026-05-08 11:52:36.876831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6bac5bb00c'
down_revision = '75acb16201ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reaction', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('reaction')

    # ### end Alembic commands ###
